### PR TITLE
Merge release/2.2.0 to master

### PR DESCRIPTION
**Pull request by spasepremcheski**
2.2.0 was released to Sonatype. We can merge this to master now

### CODE REVIEW

**Review by KCeh — APPROVED** [review]

**Comment by spasepremcheski** [comment]
The above vulnerabilities reported from SonarCloud are for the example app.

**Comment by antunflas** [comment]
> The above vulnerabilities reported from SonarCloud are for the example app.

@spasepremcheski I understand they are reported for the example app so no harm in accepting that, but I'm wondering why these activities need to be exported. Shouldn't only activities with intent-filters be exported?

**Comment by spasepremcheski** [comment]
I don't know the reason behind the change (https://github.com/infinum/Android-Goldfinger/pull/80). We should definitely take a look into this

**Comment by KCeh** [comment]
> I don't know the reason behind the change (#80). We should definitely take a look into this

You can open task for yourself on Goldfinger board

**Pull request merged**
