### PR TITLE
Change namespace to com.infinum

### PR DESCRIPTION
**Pull request by spasepremcheski**
I have updated the namespace to 'com.infinum'. Please verify that there is no other place that still uses the 'co.infinum' namespace.

One dilemma here is I should rename the package name from 'co.infinum.goldfinger' to 'com.infinum.goldfinger'. The same goes for the example app 'co.infinum.example' to 'com.infinum.example'. Since the example app is not published anywhere and we use it only to test the library, I guess it doesn't matter. And for the library, I think we should change it so that the imports don't look like this: 
`import co.infinum.goldfinger.Goldfinger`

What do you think @margaritajankovska @KCeh

### CODE REVIEW

**Comment by antunflas** [comment]
Just to let you know, changing the package name will require import changes in all projects using the library, making this change backward-incompatible, and therefore, the major version should change.

Considering the only benefit is being consistent in the package name with the namespace, a drawback is forcing users to do the import changes, we should weigh what makes the most sense. I don't have a side yet :D

**Comment by spasepremcheski** [comment]
@antunflas you are right. Maybe we should consider and do the package name change when we do a major version increase.

**Comment by KCeh** [comment]
> @antunflas you are right. Maybe we should consider and do the package name change when we do a major version increase.

I agree. Let's keep the current package name to avoid additional work (for us and users). If there is time in the future we can refactor it then.
Unless, someone has strong option for changing package naem

**Comment by KCeh** [comment]
> I have updated the namespace to 'com.infinum'. Please verify that there is no other place that still uses the 'co.infinum' namespace.

When you publish to staging/mavenLocal you will see if coordinates are correct (com.infinum instead of co.infinum)

**Comment by spasepremcheski** [comment]
I did publish it locally and it indeed is 'com.infinum.goldfinger' and 'com.infinum.goldfinger-rx'

**Review by KCeh — APPROVED** [review]

**Pull request merged**
